# Generated by Django 4.2 on 2025-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='Default Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
